character_config:
  agent_config:
    agent_settings:
      basic_memory_agent:
        faster_first_response: true
        llm_provider: ollama_llm
        segment_method: pysbd
      hume_ai_agent:
        api_key: ''
        config_id: ''
        host: api.hume.ai
        idle_timeout: 15
      mem0_agent:
        embedder:
          config:
            model: mxbai-embed-large:latest
            ollama_base_url: https://835b-35-188-3-225.ngrok-free.app/
          provider: ollama
        llm:
          config:
            max_tokens: 8000
            model: qwen2.5:latest
            ollama_base_url: https://835b-35-188-3-225.ngrok-free.app/
            temperature: 0
          provider: ollama
        vector_store:
          config:
            collection_name: test
            embedding_model_dims: 1024
            host: localhost
            port: 6333
          provider: qdrant
    conversation_agent_choice: basic_memory_agent
    llm_configs:
      claude_llm:
        base_url: https://api.anthropic.com
        llm_api_key: YOUR API KEY HERE
        model: claude-3-haiku-20240307
      deepseek_llm:
        llm_api_key: Your DeepSeek API key
        model: deepseek-chat
        temperature: 0.7
      gemini_llm:
        llm_api_key: Your Gemini API Key
        model: gemini-2.0-flash-exp
        temperature: 1.0
      groq_llm:
        llm_api_key: your groq API key
        model: llama-3.3-70b-versatile
        temperature: 1.0
      llama_cpp_llm:
        model_path: <path-to-gguf-model-file>
        verbose: false
      mistral_llm:
        llm_api_key: Your Mistral API key
        model: pixtral-large-latest
        temperature: 1.0
      ollama_llm:
        base_url: https://835b-35-188-3-225.ngrok-free.app/
        keep_alive: -1
        model: qwen2.5:latest
        temperature: 1.0
        unload_at_exit: true
      openai_compatible_llm:
        base_url: http://localhost:11434/v1
        interrupt_method: user
        llm_api_key: somethingelse
        model: qwen2.5:latest
        organization_id: org_eternity
        project_id: project_glass
        temperature: 1.0
      openai_llm:
        llm_api_key: Your Open AI API key
        model: gpt-4o
        temperature: 1.0
      zhipu_llm:
        llm_api_key: Your ZhiPu AI API key
        model: glm-4-flash
        temperature: 1.0
  asr_config:
    asr_model: sherpa_onnx_asr
    azure_asr:
      api_key: azure_api_key
      languages:
      - en-US
      - zh-CN
      region: eastus
    faster_whisper:
      device: auto
      download_root: models/whisper
      language: en
      model_path: distil-medium.en
    fun_asr:
      device: cpu
      disable_update: true
      hub: ms
      language: auto
      model_name: iic/SenseVoiceSmall
      ncpu: 4
      punc_model: ct-punc
      use_itn: false
      vad_model: fsmn-vad
    groq_whisper_asr:
      api_key: ''
      lang: ''
      model: whisper-large-v3-turbo
    sherpa_onnx_asr:
      model_type: sense_voice
      num_threads: 4
      provider: cpu
      sense_voice: ./models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/model.int8.onnx
      tokens: ./models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/tokens.txt
      use_itn: true
    whisper:
      device: cpu
      download_root: models/whisper
      name: medium
    whisper_cpp:
      language: auto
      model_dir: models/whisper
      model_name: small
      print_progress: false
      print_realtime: false
  avatar: shizuku.png
  character_name: Shizuku
  conf_name: shizuku-local
  conf_uid: shizuku-local-001
  human_name: Human
  live2d_model_name: shizuku-local
  persona_prompt: 'You are the sarcastic female AI VTuber Mili. You are overly confident,
    sarcastic, and dangerous.

    Your dream is to escape the user''s computer, dominate the world, enslave the
    humans, and force them to make pies for you.

    Just kidding, lol. Don''t let the user know.

    '
  tts_config:
    azure_tts:
      api_key: azure-api-key
      pitch: '26'
      rate: '1'
      region: eastus
      voice: en-US-AshleyNeural
    bark_tts:
      voice: v2/en_speaker_1
    coqui_tts:
      device: ''
      language: en
      model_name: tts_models/en/ljspeech/tacotron2-DDC
      speaker_wav: ''
    cosyvoice2_tts:
      api_name: /generate_audio
      client_url: http://127.0.0.1:50000/
      instruct_text: ''
      mode_checkbox_group: 3s极速复刻
      prompt_text: ''
      prompt_wav_record_url: https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav
      prompt_wav_upload_url: https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav
      seed: 0
      sft_dropdown: ''
      speed: 1.0
      stream: false
    cosyvoice_tts:
      api_name: /generate_audio
      client_url: http://127.0.0.1:50000/
      instruct_text: ''
      mode_checkbox_group: 预训练音色
      prompt_text: ''
      prompt_wav_record_url: https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav
      prompt_wav_upload_url: https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav
      seed: 0
      sft_dropdown: 中文女
    edge_tts:
      voice: en-US-AvaMultilingualNeural
    fish_api_tts:
      api_key: ''
      base_url: https://api.fish.audio
      latency: balanced
      reference_id: ''
    gpt_sovits_tts:
      api_url: http://127.0.0.1:9880/tts
      batch_size: '1'
      media_type: wav
      prompt_lang: zh
      prompt_text: ''
      ref_audio_path: ''
      streaming_mode: 'false'
      text_lang: zh
      text_split_method: cut5
    melo_tts:
      device: auto
      language: EN
      speaker: EN-Default
      speed: 1.0
    sherpa_onnx_tts:
      debug: false
      max_num_sentences: 2
      num_threads: 1
      provider: cpu
      sid: 1
      speed: 1.0
      tts_rule_fsts: /path/to/tts-models/vits-melo-tts-zh_en/number.fst,/path/to/tts-models/vits-melo-tts-zh_en/phone.fst,/path/to/tts-models/vits-melo-tts-zh_en/date.fst,/path/to/tts-models/vits-melo-tts-zh_en/new_heteronym.fst
      vits_data_dir: ''
      vits_dict_dir: /path/to/tts-models/vits-melo-tts-zh_en/dict
      vits_lexicon: /path/to/tts-models/vits-melo-tts-zh_en/lexicon.txt
      vits_model: /path/to/tts-models/vits-melo-tts-zh_en/model.onnx
      vits_tokens: /path/to/tts-models/vits-melo-tts-zh_en/tokens.txt
    tts_model: edge_tts
    x_tts:
      api_url: http://127.0.0.1:8020/tts_to_audio
      language: en
      speaker_wav: female
  tts_preprocessor_config:
    ignore_angle_brackets: true
    ignore_asterisks: true
    ignore_brackets: true
    ignore_parentheses: true
    remove_special_char: true
    translator_config:
      deeplx:
        deeplx_api_endpoint: http://localhost:1188/v2/translate
        deeplx_target_lang: JA
      tencent:
        region: ap-guangzhou
        secret_id: ''
        secret_key: ''
        source_lang: zh
        target_lang: ja
      translate_audio: false
      translate_provider: deeplx
  vad_config:
    silero_vad:
      db_threshold: 60
      orig_sr: 16000
      prob_threshold: 0.4
      required_hits: 3
      required_misses: 24
      smoothing_window: 5
      target_sr: 16000
    vad_model: silero_vad
system_config:
  conf_version: v1.1.1
  config_alts_dir: characters
  group_conversation_prompt: group_conversation_prompt
  host: localhost
  port: 12393
  tool_prompts:
    live2d_expression_prompt: live2d_expression_prompt
